'use strict';

// Unit tests for src/middleware/auditLog.js

const mockStoreAuditEntry = jest.fn().mockResolvedValue(undefined);
jest.mock('../../src/persistence', () => ({
    storeAuditEntry: (...args) => mockStoreAuditEntry(...args),
}));

jest.mock('uuid', () => ({ v4: () => 'test-uuid-1234' }));

const { auditLog } = require('../../src/middleware/auditLog');

function makeRes(statusCode = 200) {
    const res = {
        statusCode,
        json: jest.fn(function (body) { return this; }),
        sendStatus: jest.fn(function (code) { this.statusCode = code; return this; }),
    };
    return res;
}

function makeReq(user = { id: 'u1', email: 'admin@test.com', role: 'admin' }, params = {}) {
    return { user, params };
}

describe('auditLog middleware', () => {
    beforeEach(() => {
        mockStoreAuditEntry.mockClear();
    });

    test('calls next() immediately', () => {
        const mw = auditLog('CREATE', 'resident', () => 'r1', () => 'Created resident');
        const next = jest.fn();
        mw(makeReq(), makeRes(), next);
        expect(next).toHaveBeenCalledTimes(1);
    });

    test('wraps res.json — storeAuditEntry called on 2xx response', async () => {
        const mw = auditLog('CREATE', 'resident', (_req, body) => body.id, (_req, body) => `Created ${body.name}`);
        const res = makeRes(201);
        const next = jest.fn();
        mw(makeReq(), res, next);

        res.json({ id: 'r42', name: 'Alice' });

        await new Promise(r => setImmediate(r)); // let the .catch() promise settle
        expect(mockStoreAuditEntry).toHaveBeenCalledTimes(1);
        const [entry] = mockStoreAuditEntry.mock.calls[0];
        expect(entry.action).toBe('CREATE');
        expect(entry.resource_type).toBe('resident');
        expect(entry.resource_id).toBe('r42');
        expect(entry.summary).toBe('Created Alice');
        expect(entry.user_email).toBe('admin@test.com');
        expect(entry.user_role).toBe('admin');
    });

    test('wraps res.sendStatus — storeAuditEntry called on sendStatus(200)', async () => {
        const mw = auditLog('DELETE', 'resident', (req) => req.params.id, (req) => `Deleted ${req.params.id}`);
        const res = makeRes(200);
        const req = makeReq(undefined, { id: 'r99' });
        req.user = { id: 'u1', email: 'admin@test.com', role: 'admin' };
        const next = jest.fn();
        mw(req, res, next);

        res.sendStatus(200);

        await new Promise(r => setImmediate(r));
        expect(mockStoreAuditEntry).toHaveBeenCalledTimes(1);
        const [entry] = mockStoreAuditEntry.mock.calls[0];
        expect(entry.action).toBe('DELETE');
        expect(entry.resource_id).toBe('r99');
    });

    test('does NOT call storeAuditEntry on 4xx json response', async () => {
        const mw = auditLog('CREATE', 'resident', () => 'x', () => 'x');
        const res = makeRes(400);
        res.statusCode = 400;
        const next = jest.fn();
        mw(makeReq(), res, next);

        res.json({ error: 'Bad request' });

        await new Promise(r => setImmediate(r));
        expect(mockStoreAuditEntry).not.toHaveBeenCalled();
    });

    test('does NOT call storeAuditEntry when req.user is absent', async () => {
        const mw = auditLog('CREATE', 'resident', () => 'x', () => 'x');
        const res = makeRes(201);
        const req = { params: {} }; // no .user
        const next = jest.fn();
        mw(req, res, next);

        res.json({ id: 'r1' });

        await new Promise(r => setImmediate(r));
        expect(mockStoreAuditEntry).not.toHaveBeenCalled();
    });

    test('still calls original res.json after intercepting', () => {
        const mw = auditLog('UPDATE', 'resident', () => 'r1', () => 'Updated');
        const origJson = jest.fn();
        const res = makeRes(200);
        res.json = origJson;
        res.json.bind = () => origJson; // mock bind
        const next = jest.fn();
        mw(makeReq(), res, next);

        res.json({ id: 'r1' });
        expect(origJson).toHaveBeenCalledWith({ id: 'r1' });
    });

    test('still calls original res.sendStatus after intercepting', () => {
        const mw = auditLog('DELETE', 'resident', () => 'r1', () => 'Deleted');
        const origSendStatus = jest.fn();
        const res = makeRes(200);
        res.sendStatus = origSendStatus;
        res.sendStatus.bind = () => origSendStatus;
        const next = jest.fn();
        mw(makeReq(), res, next);

        res.sendStatus(200);
        expect(origSendStatus).toHaveBeenCalledWith(200);
    });

    test('stores the uuid generated by uuidv4', async () => {
        const mw = auditLog('CREATE', 'doc', () => 'd1', () => 'Doc created');
        const res = makeRes(201);
        const next = jest.fn();
        mw(makeReq(), res, next);
        res.json({ id: 'd1' });

        await new Promise(r => setImmediate(r));
        const [entry] = mockStoreAuditEntry.mock.calls[0];
        expect(entry.id).toBe('test-uuid-1234');
    });
});
